spring.application.name=b2b-inventory-api
server.port=8081
spring.datasource.url=jdbc:h2:mem:b2b_inventory
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# Override with AUTH_API_URL env variable in Docker
auth.api.url=${AUTH_API_URL:http://localhost:8080}