spring.application.name=auth-api
# Enable the H2 Console (The web interface)
spring.h2.console.enabled=true
# The URL to access it in your browser
spring.datasource.url=jdbc:h2:mem:authdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# This ensures the database doesn't disappear if the connection blips
spring.jpa.hibernate.ddl-auto=update