spring.application.name=auth-api
spring.datasource.url=mysql://root:ptiMFPCcoDMTZpodGUPZcfEZLcbAHFar@mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=ptiMFPCcoDMTZpodGUPZcfEZLcbAHFar